const projects = [
    {
        id: 0,
        github: 'https://github.com/ammann64/javascript-coding-quiz',
        name: 'Javascript Coding Quiz',
        image: '/assets/img/javascript-quiz.png',
        altText: 'A screenshot of the starting screen of the quiz. There is a high score button in the top right, a description of the quiz, then a start quiz button at the bottom',
        deployed: 'https://ammann64.github.io/javascript-coding-quiz/',
    },
    {
        id: 1,
        github: 'https://github.com/ammann64/password-generator',
        name: 'Password Generator',
        image: '/assets/img/password-generator.png',
        altText: 'A password generator with some example output shown, and with a generate button below',
        deployed: 'https://ammann64.github.io/password-generator/',
    },
    {
        id : 2,
        github: 'https://github.com/ammann64/note-taking-app',
        name: 'Note Taking App',
        image: '/assets/img/note-taker.png',
        altText: 'A note taking app with some example notes with delete buttons beside',
        deployed: 'https://protected-waters-52777-a17f0115b214.herokuapp.com/',
    },
    {
        id: 3,
        github: 'https://github.com/ammann64/austin-work-scheduler',
        name: 'Work Scheduler',
        image: '/assets/img/work-scheduler.png',
        altText: 'An empty work scheduler with hour dividers for each hour of the work day',
        deployed: 'https://ammann64.github.io/austin-work-scheduler/'
    },
    {
        id: 4,
        github: '',
        name: 'Simple Logo Generator',
        image: '/assets/img/example-logo.png',
        altText: 'An example logo generated by the simple logo generator',
        deployed: 'https://drive.google.com/file/d/1B_mtPuO92gcut4WSFuAfvHmFFTX4gYGd/view?usp=drive_link'

    },
    {
        id: 5,
        github: 'https://github.com/ammann64/readme-generator',
        name: 'Readme Generator',
        image: '/assets/img/example-readme.png',
        altText: 'An example readme generated by the readme generator',
        deployed: '#',
    },
    {
        id: 6,
        github: 'https://github.com/https://github.com/WebDevMullins/project-3',
        name: 'AIconic, a Logo Generator',
        image: '/assets/img/aiconic.png',
        altText: 'The homepage of our website',
        deployed: 'https://project-3-8j08.onrender.com/'
    }
];

export default projects;